
import java.util.Calendar;

public class BeforeMainClass extends javax.swing.JFrame {

    /**
     * Creates new form BeforeMainClass
     */
    public BeforeMainClass() {
        initComponents();
        
    }
    Client client = new Client("admin2021477512", "xxxx000", 2, 100, 0.0, 24, 11, 2023, "amirul", 0);
    RentalCar car = new RentalCar("jmh6467", 24, 11, 2023, 28, 11, 2023, "Johor", "hutchback", 3.0, "2021477512", "2021477512");
    /*
    public RentalCar getCarInstance(){
        return car;
    }*/
    
    public String durationLabel(){
        if(client.getIsRenting()==1)
            return "Rent will end in..";
        else if(client.getIsRenting()==2)
            return "Rent will start in..";
        else 
            return "none";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextButton.setText("This Button will navigate to next page");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        DashboardClass dashboard = new DashboardClass();
        dashboard.show();
        
        dashboard.clientNameFill.setText(client.getName());
        dashboard.currentDateFill.setText(Integer.toString(client.getDay()) + "/" + Integer.toString(client.getMonth())+ "/" + Integer.toString(client.getYear()));
        dashboard.currencyFill.setText(Double.toString(client.getCurrencyWallet()));
        dashboard.numbOfRentFill.setText(Integer.toString(client.getNumbOfRentMade()));
        
        dashboard.statusButton.setText(client.translateIsRenting());
        dashboard.DurationLabel.setText(durationLabel());
        dashboard.durationButton.setText(String.valueOf(car.daysOfRentCount(client.getDay(), client.getMonth(), client.getYear())) + " Days");
        dashboard.locationButton.setText(car.getLocation());
        dashboard.carDetailButton.setText(car.getCarType());
        
        dashboard.clientPaymentButton.setText("RM"+Double.toString(car.getRentalAmountPerDays()*Double.valueOf(car.daysOfRentCount(client.getDay(), client.getMonth(), client.getYear()))));
        
        //Set Visibility of Admin Button
        if(dashboard.AdminButton.isVisible()){
            if (client.getClientID().substring(0, 5).equals("admin"))
                dashboard.AdminButton.setVisible(true);
            else
                dashboard.AdminButton.setVisible(false);
        }else{
            dashboard.AdminButton.setVisible(true);
        }
        
        dispose();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeforeMainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeforeMainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeforeMainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeforeMainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeforeMainClass().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
